# Generated by Django 5.0.6 on 2024-07-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_itemestoque_quantidade_alter_itempedido_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemestoque',
            name='cor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='banners'),
        ),
    ]
