# Generated by Django 5.0.6 on 2024-08-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_itempedido_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
